# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11integration.proto\"J\n\x10RegisterRequest_\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x13\n\x0bserver_port\x18\x02 \x01(\x05\x12\x0c\n\x04keys\x18\x03 \x03(\x05\"#\n\x11RegisterResponse_\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\rQueryRequest_\x12\x0b\n\x03key\x18\x01 \x01(\x05\":\n\x0eQueryResponse_\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x13\n\x0bserver_port\x18\x02 \x01(\x05\"\x13\n\x11TerminateRequest_\"&\n\x12TerminateResponse_\x12\x10\n\x08num_keys\x18\x01 \x01(\x05\x32\xa0\x01\n\x0bIntegration\x12\x31\n\x08Register\x12\x11.RegisterRequest_\x1a\x12.RegisterResponse_\x12(\n\x05Query\x12\x0e.QueryRequest_\x1a\x0f.QueryResponse_\x12\x34\n\tTerminate\x12\x12.TerminateRequest_\x1a\x13.TerminateResponse_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'integration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST_._serialized_start=21
  _REGISTERREQUEST_._serialized_end=95
  _REGISTERRESPONSE_._serialized_start=97
  _REGISTERRESPONSE_._serialized_end=132
  _QUERYREQUEST_._serialized_start=134
  _QUERYREQUEST_._serialized_end=162
  _QUERYRESPONSE_._serialized_start=164
  _QUERYRESPONSE_._serialized_end=222
  _TERMINATEREQUEST_._serialized_start=224
  _TERMINATEREQUEST_._serialized_end=243
  _TERMINATERESPONSE_._serialized_start=245
  _TERMINATERESPONSE_._serialized_end=283
  _INTEGRATION._serialized_start=286
  _INTEGRATION._serialized_end=446
# @@protoc_insertion_point(module_scope)
